application:
  cors:
    allowed-origins:
      - https://start.seed4j.com
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800

seed4j:
  forced-project-folder: /tmp/seed4j
